### ISSUE TITLE
 Implement GUI

### ISSUE THREAD

**Issue by ehharvey** [ehharvey/auteline#21]

**Comment by ehharvey** [comment]
@Gabeele has worked on the wireframes. Check the Discord.

**Comment by ehharvey** [comment]
We talked about delivering the frontend as a web app. This basically just means that we need to deliver a REST API

**Comment by Gabeele** [comment]
Adobe XD Wireframe as a reference - https://xd.adobe.com/view/081f4387-4de5-4d47-9f73-86b0fe9055f5-5d4c/

**Comment by ehharvey** [comment]
Testing: 
Web app: Selenium + JUnit

Swing: some libraries

**Comment by ehharvey** [comment]
For now: we're gonna go Web app w/ 
Selenium: GUI
scripts: Rest API
JUnit: server

**Comment by ehharvey** [comment]
https://spring.io/guides/tutorials/rest/

**Comment by Gabeele** [comment]
The GUI and serving is completed.
